name: CI on self-hosted runner

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 프로젝트 폴더로 이동해서 최신 코드 반영
        run: |
          cd /volume1/docker/finance-app   # NAS에 실제 코드가 있는 폴더 경로
          git fetch --all
          git reset --hard origin/master
          git clean -fd

      # 도커 php 버전 문제로 실행하지 않음
      # - name: 의존성 업데이트 (선택)
      #   run: |
      #     cd /volume1/docker/finance-app/src
      #     composer install --no-interaction --prefer-dist --optimize-autoloader
      #     php artisan migrate --force
